Add IAM components
Icerzack/terraform-provider-selectel pull request #1
Opened 2024-02-22 16:46 UTC by Icerzack

2024-02-27 09:53 UTC, Icerzack commented on go.mod
> +toolchain go1.21.4
Не очень могу понять, почему здесь автоматически меняется на `go1.21` и добавляется `toolchain`...

2024-02-27 10:22 UTC, MisterZurg commented on selectel/iam.go
> +		}
Тут конечно, немножко кодика, но может не стоит экономить на спичках, и полным словом напписать:
```suggestion
func containsServiceUsersRole(roles []serviceusers.Role, svcRole serviceusers.Role) bool {
	for _, role := range roles {
		if role == svcRole {
			return true
		}
```

2024-02-27 10:22 UTC, MisterZurg commented on selectel/iam.go
> +	}
Same

2024-02-27 10:22 UTC, MisterZurg commented on selectel/resource_selectel_iam_serviceuser_v1.go
> +		CreateContext: resourceIAMServiceUserV1Create,
В своей части, я добавил поле `Description` кажется, раз уж мы пытаемся делать и контрибьютить, то лишний раз стоит описать что это зачем 
```suggestion
return &schema.Resource{
		Description: "represents a IAMServiceUser — entity ... service",

		CreateContext: resourceIAMServiceUserV1Create,
```

2024-02-27 10:45 UTC, Icerzack commented on selectel/resource_selectel_iam_serviceuser_v1.go
> +		CreateContext: resourceIAMServiceUserV1Create,
Добавил

2024-02-27 10:45 UTC, Icerzack commented on selectel/iam.go
> +	}
Поправил

2024-02-27 10:46 UTC, Icerzack commented on selectel/iam.go
> +		}
Поправил

2024-02-27 11:20 UTC, Icerzack commented on go.mod
> +toolchain go1.21.4
Подправил командой `go get go@1.20`, оказалось, что `dbaas-go` был почему-то на `v0.10.0`, где используется `go1.21`.

2024-02-28 16:59 UTC, gusakk requested changes

2024-02-28 16:59 UTC, gusakk commented on go.mod
> -	github.com/selectel/dbaas-go v0.10.0
Не уверен, что в рамках данного PR стоит обновлять зависимость dbass-go клиента.

2024-02-28 16:59 UTC, gusakk commented on selectel/iam.go
> +	resourceFederationMap := federationSet.List()[0].(map[string]interface{})
А `TypeMap` здесь не лучше подходит вместо `TypeSet`?
У нас же только одна федерация может быть у пользователя.

2024-02-28 16:59 UTC, gusakk commented on selectel/iam.go
> +func containsServiceUsersRole(roles []serviceusers.Role, neededRole serviceusers.Role) bool {
Можно использовать `slices.Contains`.

2024-02-28 16:59 UTC, gusakk commented on selectel/iam.go
> +func containsUsersRole(roles []users.Role, neededRole users.Role) bool {
Можно использовать `slices.Contains`.

2024-02-28 16:59 UTC, gusakk commented on selectel/resource_selectel_iam_user_v1.go
> +				Description: "Authentication type of the User. Can be 'local' or 'federative'.",
Опечатка, `federated` вместо `federative`.

В секции `federation` аналогично.

2024-02-28 16:59 UTC, gusakk commented on selectel/resource_selectel_iam_user_v1.go
> +	if d.HasChange("email") || d.HasChange("auth_type") {
По-хорошему, при обновлении `federation` тоже нужно создавать пользователя.

2024-02-28 16:59 UTC, gusakk commented on selectel/provider.go
>  			"selectel_vpc_user_v2":                                  resourceVPCUserV2(),
Если мы текущем PR делаем deprecate vpc user ресурсов, то здесь тоже можно оставить коммент.

2024-02-28 16:59 UTC, gusakk commented on selectel/resource_selectel_iam_serviceuser_v1.go
> +	if d.Get("password") == "UNKNOWN" {
Может `UNKNOWN` в какую-нибудь константу вынесем? А то он используется много где.

2024-02-28 16:59 UTC, gusakk commented on selectel/resource_selectel_iam_ec2_v1.go
> +	d.Set("access_key", credential.AccessKey)
А нам действительно нужно отдельное поле `access_key`, мы не можем просто ссылаться на `Id`, если `access_key` в качестве него используется.

2024-02-28 16:59 UTC, gusakk commented on selectel/resource_selectel_iam_ec2_v1.go
> +	credentials, _ := iamClient.EC2.List(ctx, d.Get("user_id").(string))
Здесь (вероятно) забыли обработать ошибку:)

2024-02-28 16:59 UTC, gusakk commented on selectel/resource_selectel_iam_user_v1_test.go
> +					resource.TestCheckResourceAttrSet("selectel_iam_user_v1.user_tf_acc_test_1", "email"),
Можно еще `federation` куда-нибудь включить в проверки.

2024-02-28 16:59 UTC, gusakk commented on selectel/resource_selectel_vpc_role_v2.go
>  import (
Тесты для `vpc/role` и `vpc/user` тоже не нужны.

2024-02-29 09:39 UTC, Icerzack commented on go.mod
> -	github.com/selectel/dbaas-go v0.10.0
Просто `dbaas-go` на v0.10.0 имел `go1.21` (https://github.com/selectel/dbaas-go/blob/v0.10.0/go.mod) и тогда пришлось бы поднимать и `go.mod` провайдера на `go1.21`, в v0.11.1 вроде они вернули на `1.20`.

2024-02-29 13:29 UTC, Icerzack commented on selectel/iam.go
> +	resourceFederationMap := federationSet.List()[0].(map[string]interface{})
Подправил

2024-02-29 13:29 UTC, Icerzack commented on selectel/iam.go
> +func containsServiceUsersRole(roles []serviceusers.Role, neededRole serviceusers.Role) bool {
Подправил

2024-02-29 13:29 UTC, Icerzack commented on selectel/iam.go
> +func containsUsersRole(roles []users.Role, neededRole users.Role) bool {
Подправил

2024-02-29 13:30 UTC, Icerzack commented on selectel/resource_selectel_iam_user_v1.go
> +				Description: "Authentication type of the User. Can be 'local' or 'federative'.",
Подправил

2024-02-29 13:30 UTC, Icerzack commented on selectel/resource_selectel_iam_user_v1.go
> +	if d.HasChange("email") || d.HasChange("auth_type") {
В итоге, так как эти поля (и `federation` теперь) и так помечены как `ForceNew`, этот `if` я убрал

2024-02-29 13:31 UTC, Icerzack commented on selectel/provider.go
>  			"selectel_vpc_user_v2":                                  resourceVPCUserV2(),
Подправил

2024-02-29 13:31 UTC, Icerzack commented on selectel/resource_selectel_iam_serviceuser_v1.go
> +	if d.Get("password") == "UNKNOWN" {
Да, так стало лучше. Подправил

2024-02-29 13:32 UTC, Icerzack commented on selectel/resource_selectel_iam_ec2_v1.go
> +	d.Set("access_key", credential.AccessKey)
Справедливо, убрал его за ненадобностью и оставил комментарий в `Description`, что в качестве `id` ресурса используется `access_key`.

2024-02-29 13:32 UTC, Icerzack commented on selectel/resource_selectel_iam_ec2_v1.go
> +	credentials, _ := iamClient.EC2.List(ctx, d.Get("user_id").(string))
Да, подправил)

2024-02-29 13:32 UTC, icerzack commented on selectel/resource_selectel_iam_user_v1_test.go
> +					resource.TestCheckResourceAttrSet("selectel_iam_user_v1.user_tf_acc_test_1", "email"),
Добавил еще один тест кейс

2024-02-29 13:33 UTC, Icerzack commented on selectel/resource_selectel_vpc_role_v2.go
>  import (
Убрал их, но заметил, что некоторые методы `vpc/user` использовались в `vpc/keypair`, поэтому, заменил также удаленные `vpc/user` на новый `iam/serviceuser` в этом самом `vpc/keypair`

2024-03-01 08:20 UTC, saydamir requested changes

2024-03-01 08:20 UTC, saydamir commented on selectel/resource_selectel_iam_serviceuser_v1.go
> +	}
```suggestion
	password = d.Get("password").(string)
	if password == "UNKNOWN" {
		password = ""
	}
```

2024-03-01 08:20 UTC, saydamir commented on selectel/iam.go
> +func containsServiceUsersRole(roles []serviceusers.Role, neededRole serviceusers.Role) bool {
Тут видимо надо тогда сначала обновиться go.mod на 1.21? `slices` доступен только с этой версии.

2024-03-01 08:20 UTC, saydamir commented on selectel/iam.go
> +	if rolesSet.Len() == 0 {
Вроде лишняя проверка. Давай уберем?

2024-03-01 08:20 UTC, saydamir commented on selectel/iam.go
> +func getIAMUserRolesFromSet(rolesSet *schema.Set) ([]users.Role, error) {
convertIAMUserRoles() ?

2024-03-01 08:20 UTC, saydamir commented on selectel/iam.go
> +			RoleName:  users.RoleName(strings.ToLower(roleName)),
Нам тут точно нужен ToLower? Что мы с его помощью хотим решить?

2024-03-01 08:20 UTC, saydamir commented on selectel/iam.go
> +		resourceRoleMap := rolesList[i].(map[string]interface{})
Можем сразу кастануть к `map[string]string` и проверить что каст успешный? Тогда не нужно будет `roleNameRaw`?

2024-03-01 08:20 UTC, saydamir commented on selectel/iam.go
> +	roles := make([]users.Role, len(rolesList))
Может быть в iam-go сделаем `Role` общей структурой и для `Users` и `ServiceUser`? В будущем еще понадобятся группы.
Тогда не нужно будет дублировать все функции в этом пакете.
@gusakk

2024-03-01 08:20 UTC, saydamir commented on selectel/resource_selectel_iam_serviceuser_v1.go
> +	if err != nil {
Ошибку нужно проверить перед входом в `if d.HasChange("role")` ?

2024-03-01 08:20 UTC, saydamir commented on selectel/resource_selectel_iam_serviceuser_v1.go
> +		}
Можно вынести в `iam.go` и написать unit-test?

2024-03-01 08:20 UTC, saydamir commented on selectel/resource_selectel_iam_serviceuser_v1.go
> +			d.SetId("")
У нас не должно быть одинаковое поведение если пользователя уже нет и если мы его удалили? 

Если должно быть, то можно исправить на:
```suggestion
	if err != nil && !errors.Is(err, iamerrors.ErrUserNotFound){
		return diag.FromErr(errDeletingObject(objectServiceUser, d.Id(), err))
	}
	
	d.SetId("")
	return nil
```

`d.SetId("")` нужен при delete?

2024-03-01 08:20 UTC, saydamir commented on selectel/resource_selectel_vpc_keypair_v2_test.go
> +		user    serviceusers.ServiceUser
В гайде по миграции не нужно учесть, что `resource_selectel_vpc_user` мог использоваться в других ресурсах?

2024-03-01 08:20 UTC, saydamir commented on selectel/resource_selectel_vpc_user_v2.go
> +				Optional: true,
Специально изменено?

2024-03-01 08:20 UTC, saydamir commented on selectel/resource_selectel_iam_ec2_v1.go
> +			"secret_key": {
Sensitive?

2024-03-01 08:20 UTC, saydamir commented on selectel/resource_selectel_iam_serviceuser_v1.go
> +			"password": {
Sensitive?

2024-03-01 08:20 UTC, saydamir commented on selectel/resource_selectel_iam_user_v1.go
> +					Type: schema.TypeString,
Нам тут не надо явно указать все поля?

2024-03-01 08:20 UTC, saydamir commented on selectel/resource_selectel_iam_user_v1.go
> +		Schema: map[string]*schema.Schema{
validateFunc не нужен, чтобы проверить, что если указан auth_type = local, то не должно быть federation и наоброт?

2024-03-01 08:20 UTC, saydamir commented on selectel/resource_selectel_iam_user_v1.go
> +				Type:        schema.TypeMap,
ForceNew: true?

2024-03-01 08:20 UTC, saydamir commented on selectel/iam.go
> +	unknownFieldValue = "UNKNOWN"
Давай и в имя и в значение напишем что-то про то что это используется только при импорте?
Возможно нужно так же добавить iam куда-то в имя переменной, если оно планируется использоваться только в IAM ресурсах.

2024-03-01 08:20 UTC, saydamir commented on selectel/iam.go
> +func flattenIAMServiceUserRoles(roles []serviceusers.Role) []interface{} {
Вроде бы все 3 метода не flatten, а конвертация из одного типа в интерфейс?

2024-03-01 08:56 UTC, gusakk commented on selectel/iam.go
> +	roles := make([]users.Role, len(rolesList))
Я не помню откуда у нас появилось две одинаковых структуры для пользователей и сервисных пользователей (возможно к SDK я какой-то коммент по этому поводу писал, но не уверен), решил здесь не оставлять этот комментарий:)

Кажется, что необходимости в этом действительно нет, можно сделать общую структуру.

2024-03-01 08:59 UTC, gusakk commented on go.mod
> -	github.com/selectel/dbaas-go v0.10.0
@Icerzack , а почему в официальной версии провайдера используется 1.20 при v0.10.0?
https://github.com/selectel/terraform-provider-selectel/blob/master/go.mod#L3

2024-03-01 09:06 UTC, gusakk commented on selectel/iam.go
> +func containsServiceUsersRole(roles []serviceusers.Role, neededRole serviceusers.Role) bool {
Эх:)
Я бы предложил не обновлять версию в рамках текущего PR'а.

2024-03-01 12:23 UTC, Icerzack commented on go.mod
> -	github.com/selectel/dbaas-go v0.10.0
В общем, подождем вот этого PR в основную репу, и потом синк сделаем, там они поправили эту версию тоже)
https://github.com/selectel/terraform-provider-selectel/pull/251/files#

2024-03-01 12:27 UTC, Icerzack commented on selectel/iam.go
> +func containsServiceUsersRole(roles []serviceusers.Role, neededRole serviceusers.Role) bool {
Тогда вернем как было (но уже теперь с одним форматом ролей)?

2024-03-01 12:58 UTC, icerzack commented on selectel/iam.go
> +			RoleName:  users.RoleName(strings.ToLower(roleName)),
Если будет введено например `Account`, когда ожидалось `account` на месте `scope`, например)

2024-03-01 13:01 UTC, Icerzack commented on selectel/resource_selectel_iam_user_v1.go
> +		Schema: map[string]*schema.Schema{
Да, в целом, можно написать)

2024-03-01 13:03 UTC, Icerzack commented on selectel/resource_selectel_iam_user_v1.go
> +					Type: schema.TypeString,
Да, в `TypeMap` нельзя указывать конкрентые значения( Вот ссылка, желтый блок Note: https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-types#typemap

2024-03-01 13:04 UTC, Icerzack commented on selectel/resource_selectel_vpc_user_v2.go
> +				Optional: true,
нет, случайно, не заметил))

2024-03-01 13:06 UTC, Icerzack commented on selectel/resource_selectel_vpc_keypair_v2_test.go
> +		user    serviceusers.ServiceUser
Вроде как выяснилось, что только в `vpc/keypair`, но отметить это в доке надо, да

2024-03-01 13:55 UTC, icerzack commented on selectel/resource_selectel_iam_serviceuser_v1.go
> +			d.SetId("")
Еща раз пересмотрел код, он, в целом, не нужен в `delete`-методах, поэтому `d.SetId("")` убрал совсем

2024-03-01 14:38 UTC, saydamir commented on selectel/iam.go
> +func containsServiceUsersRole(roles []serviceusers.Role, neededRole serviceusers.Role) bool {
@Icerzack я написал @truepack , можно отдельным PR прямо щас закинуть обновление до 1.21 в апстрим и не включать его в этот.

2024-03-01 14:39 UTC, Icerzack commented on selectel/iam.go
> +	roles := make([]users.Role, len(rolesList))
Готово, в [iam-go@v0.1.2](https://github.com/selectel/iam-go/tree/v0.1.2) это пофиксили)

2024-03-01 14:41 UTC, Icerzack commented on selectel/resource_selectel_iam_serviceuser_v1.go
> +	if err != nil {
Да, разумеется)

2024-03-01 14:41 UTC, Icerzack commented on selectel/resource_selectel_iam_serviceuser_v1.go
> +		}
На проверку правильного assign/unassign ролей?

2024-03-01 16:16 UTC, Icerzack commented on selectel/iam.go
> +		resourceRoleMap := rolesList[i].(map[string]interface{})
Пробовал по разному, но результаты странные. При запуске `terraform apply` все отрабатывает успешно (если сделать каст сразу к `map[string]string`). Но при запуске ACC тестов падает с ошибкой `interface conversion: interface {} is map[string]interface {}, not map[string]string`.

2024-03-01 16:38 UTC, Icerzack commented on selectel/iam.go
> +	unknownFieldValue = "UNKNOWN"
Переделал на `importFailedIAMFieldValue = "IMPORT_FAILED"`

2024-03-04 10:56 UTC, Icerzack commented on selectel/resource_selectel_iam_user_v1.go
> +		Schema: map[string]*schema.Schema{
Изучил вопрос, оказывается `ValidateFunc` не может проверять значение других полей, поэтому накинул проверки на разрешенные `roles\auth_type` и добавил условие на `federated` + `federation{}` в `Create`.

2024-03-04 10:57 UTC, Icerzack commented on selectel/iam.go
> +func flattenIAMServiceUserRoles(roles []serviceusers.Role) []interface{} {
Переписал названия всех конвертеров на более подходящие)

2024-03-04 10:58 UTC, Icerzack commented
Добавил документацию по компонентам. Гайд по миграции еще в процессе.

2024-03-06 12:45 UTC, saydamir commented on selectel/resource_selectel_iam_serviceuser_v1.go
> +							ValidateFunc: validation.StringInSlice([]string{
Не думаю что нужно такие валидации делать, т.к. в случае появления новой роли придется обновлять провайдер.
Наверно тоже самое и для scope.

2024-03-06 12:45 UTC, saydamir commented on selectel/resource_selectel_iam_ec2_v1.go
> +	log.Print(msgCreate(objectEC2Credentials, credential))
Мы тут лишнего(secret_key) не выводим?

2024-03-06 12:45 UTC, saydamir commented on selectel/resource_selectel_iam_ec2_v1.go
> +	for _, c := range credentials {
Если креды в ответе не будут найдены, то здесь же ничего не упадет и креды заполнятся пустыми `name` и `project_id`?

2024-03-06 12:45 UTC, saydamir commented on selectel/resource_selectel_iam_ec2_v1.go
> +	return nil
Тут надо как у user'ов сделать код:
```suggestion
	if err != nil && !errors.Is(err, iamerrors.ErrCredentialNotFound) {
		return diag.FromErr(errDeletingObject(objectEC2Credentials, d.Id(), err))
	}
	return nil
```

2024-03-06 12:45 UTC, saydamir commented on selectel/resource_selectel_iam_serviceuser_v1.go
> +	if password == "UNKNOWN" {
```suggestion
	if password == importIAMFieldValueFailed {
```

2024-03-06 12:45 UTC, saydamir commented on selectel/resource_selectel_iam_user_v1.go
> +		Schema: map[string]*schema.Schema{
> накинул проверки на разрешенные roles\auth_type
- думаю это лишнее, т.к. при добавлении новых полей клиентам обязательно придется обновлять провайдер, чтобы ими воспользоваться

> добавил условие на federated + federation{} в Create.
Смысл кажется нет, если эта проверка не производится до вызова terraform apply. Проще уж с бекенда ошибку выплюнуть тогда.

2024-03-06 12:45 UTC, saydamir commented on selectel/resource_selectel_iam_user_v1.go
> +				Description: "Federation data of the User. Can be set only if 'auth_type' is 'federated'.",
Скорее не `can be`, а должен быть установлен, для auth_type federated.

2024-03-06 12:45 UTC, saydamir commented on selectel/resource_selectel_iam_user_v1.go
> +				Default:     "local",
Дефолт можно указать как `users.Local`

2024-03-06 12:45 UTC, saydamir commented on selectel/iam.go
> +func flattenIAMUserFederation(federation *users.Federation) map[string]interface{} {
Остался flatten

2024-03-06 12:45 UTC, saydamir commented on selectel/resource_selectel_iam_serviceuser_v1.go
> +		}
Теперь тут общий код для двух ресурсов. Можно вынести в отдельную функцию и написать на нее чуть-чуть юнит тестов

2024-03-06 12:45 UTC, saydamir commented on selectel/resource_selectel_iam_user_v1.go
> +					Type: schema.TypeString,
Была идея, что federation вместо Map с неописанным набором полей, можно сделать Resource у которого явно указаны два обязательных поля.

2024-03-06 12:45 UTC, saydamir commented on selectel/iam.go
> +	unknownFieldValue = "UNKNOWN"
Давай исправим на что-то типа недоступно или неопределено во время импорта, т.к. для нас это не ошибка, а ожидаемое значение.

2024-03-06 14:15 UTC, Icerzack commented on selectel/iam.go
> +func containsServiceUsersRole(roles []serviceusers.Role, neededRole serviceusers.Role) bool {
Приняли решение, что закинем отдельным PR обновление версии на 1.21, и оставим подход через `slices.Contains`

2024-03-07 11:49 UTC, Icerzack commented on selectel/resource_selectel_iam_ec2_v1.go
> +	log.Print(msgCreate(objectEC2Credentials, credential))
Вроде как решили, что будем просто выводить id

2024-03-07 11:52 UTC, Icerzack commented on selectel/resource_selectel_iam_ec2_v1.go
> +	for _, c := range credentials {
Да, это неверно) Тогда просто будем делать d.SetId(""); и кидать ошибку)

2024-03-07 12:11 UTC, Icerzack commented on selectel/resource_selectel_iam_user_v1.go
> +					Type: schema.TypeString,
Вроде как не получится, если только не делать отдельный ресурс. У `Type` ожидаемый набор значений это:

- TypeBool - bool
- TypeInt - int
- TypeFloat - float64
- TypeString - string
- TypeList - []interface{}
- TypeMap - map[string]interface{}
- TypeSet - *schema.Set

Можно сделать через `TypeSet\TypeList`, но тогда нужно будет прописывать ограничение в коде на max 1 блок такой. С `TypeMap` таких проблем нет, но там все равно надо прописывать ограничение в коде, но уже на наличие необходимых полей.

2024-03-11 13:21 UTC, saydamir commented on website/docs/guides/migrating_from_vpc_user_to_iam_serviceuser.html.markdown
> +page_title: "Migrating from vpc_user_v2/vpc_roles_v2 to iam_serviceuser_v1"
Я бы назвал гайд как миграция на новую мажорную версию.

2024-03-11 13:21 UTC, saydamir commented on selectel/resource_selectel_iam_user_v1.go
> +					Type: schema.TypeString,
Да, давай TypeList и max 1.

2024-03-11 13:48 UTC, saydamir commented on website/docs/guides/migrating_from_vpc_user_to_iam_serviceuser.html.markdown
> +1. Remove the existing resources from the _.tfstate_ file
Тут может быть предложить убедиться что есть бекап _.tfstate_ на всякий случай?  
В отличие от манифестов он не в гите.

2024-03-11 13:48 UTC, saydamir commented on website/docs/guides/migrating_from_vpc_user_to_iam_serviceuser.html.markdown
> +    You can add multiple roles. For example, if the _selectel_vpc_user_v2_ is, let's say, _Project Administrator_ and _IAM Administrator_, then the resulting resource should look like this:
Кажется про _IAM Administrator_ это уже лишнее, т.к. раньше такой роли у него не могло быть в манифесте. Лучше указать в примере 2 роли _Project Administrator_ .

2024-03-11 13:48 UTC, saydamir commented on website/docs/guides/migrating_from_vpc_user_to_iam_serviceuser.html.markdown
> +    To import an existing service user, we need to know its ID. It can be previously obtained from _.tfstate_ before running _terraform state rm_ command, or from _my.selectel_ panel, or in some othe
Кажется странным рекомендовать посмотреть в стейте, который ты удалил 2 шага назад :)
Может быть тогда перед удалением показать как получить из state id пользователей?

2024-03-11 13:48 UTC, saydamir commented on website/docs/guides/migrating_from_vpc_user_to_iam_serviceuser.html.markdown
> +    After this, your _.tfstate_ will contain the _selectel_iam_serviceuser_v1_ resource information, but the **password field will be set to "IMPORT_FAILED"**, because Terraform can't retrieve it fro
Тут обновили текст с _IMPORT_FAILED_

2024-03-11 13:48 UTC, saydamir commented on website/docs/guides/migrating_from_vpc_user_to_iam_serviceuser.html.markdown
> +    After this, your _.tfstate_ will contain the _selectel_iam_serviceuser_v1_ resource information, but the **password field will be set to "IMPORT_FAILED"**, because Terraform can't retrieve it fro
Лучше написать "потому что пароль не хранится на сервере"

2024-03-11 13:48 UTC, saydamir commented on website/docs/guides/migrating_from_vpc_user_to_iam_serviceuser.html.markdown
> +    ~ resource "selectel_iam_serviceuser_v1" "service_user" {
Можно дописать, что если тут кроме пароля предлагает что-то поменять, например удалить роли, значит не все установленные роли были указаны в манифесте и нужно их добавить.

2024-03-11 13:48 UTC, saydamir commented on website/docs/guides/migrating_from_vpc_user_to_iam_serviceuser.html.markdown
> +    After this, the correct password will be set in _.tfstate_ for this service user and the migration from _selectel_vpc_user_v2_ and _selectel_vpc_role_v2_ to _selectel_iam_serviceuser_v1_ can be c
Я бы еще рассмотрел где-то внизу вариант, что старый ресурс использовался как зависимость для других ресурсов, например Keypairs. Какая будет ошибка и что нужно сделать.

2024-03-11 13:48 UTC, saydamir commented on website/docs/guides/migrating_from_vpc_user_to_iam_serviceuser.html.markdown
> +resource "selectel_vpc_user_v2" "service_user" {
Я бы тут назвал как-нибудь `my_service_user/sample_user/our_user/test_user`, чтобы было понятно ниже в команде `terraform state rm`, что это переменная ее часть.

2024-03-11 15:58 UTC, Icerzack commented on website/docs/guides/migrating_from_vpc_user_to_iam_serviceuser.html.markdown
> +page_title: "Migrating from vpc_user_v2/vpc_roles_v2 to iam_serviceuser_v1"
Поменял на более подходящее название, отражает теперь переход на 5.0.0

2024-03-11 15:58 UTC, Icerzack commented on website/docs/guides/migrating_from_vpc_user_to_iam_serviceuser.html.markdown
> +1. Remove the existing resources from the _.tfstate_ file
Расписал это как предупреждение (Note)

2024-03-11 15:59 UTC, icerzack commented on website/docs/guides/migrating_from_vpc_user_to_iam_serviceuser.html.markdown
> +    You can add multiple roles. For example, if the _selectel_vpc_user_v2_ is, let's say, _Project Administrator_ and _IAM Administrator_, then the resulting resource should look like this:
Изначальная идея была, что например некоторые роли заданы через панель, и при переносе их надо тоже учесть, но в целом, это расписано в разделе про импорт, так что да, подправил)

2024-03-11 16:00 UTC, icerzack commented on website/docs/guides/migrating_from_vpc_user_to_iam_serviceuser.html.markdown
> +    To import an existing service user, we need to know its ID. It can be previously obtained from _.tfstate_ before running _terraform state rm_ command, or from _my.selectel_ panel, or in some othe
Да, поэтому вынес этот раздел сразу в 1ый шаг теперь)))

2024-03-11 16:00 UTC, icerzack commented on website/docs/guides/migrating_from_vpc_user_to_iam_serviceuser.html.markdown
> +    After this, your _.tfstate_ will contain the _selectel_iam_serviceuser_v1_ resource information, but the **password field will be set to "IMPORT_FAILED"**, because Terraform can't retrieve it fro
Подправил

2024-03-11 16:00 UTC, Icerzack commented on website/docs/guides/migrating_from_vpc_user_to_iam_serviceuser.html.markdown
> +    After this, your _.tfstate_ will contain the _selectel_iam_serviceuser_v1_ resource information, but the **password field will be set to "IMPORT_FAILED"**, because Terraform can't retrieve it fro
Угу, добавил

2024-03-11 16:00 UTC, Icerzack commented on website/docs/guides/migrating_from_vpc_user_to_iam_serviceuser.html.markdown
> +    ~ resource "selectel_iam_serviceuser_v1" "service_user" {
Вынес как плашечку Note

2024-03-11 16:00 UTC, Icerzack commented on website/docs/guides/migrating_from_vpc_user_to_iam_serviceuser.html.markdown
> +    After this, the correct password will be set in _.tfstate_ for this service user and the migration from _selectel_vpc_user_v2_ and _selectel_vpc_role_v2_ to _selectel_iam_serviceuser_v1_ can be c
Ну, по сути, вроде keypair только и был в явных зависимостях, упомянул о нем

2024-03-11 16:01 UTC, Icerzack commented on website/docs/guides/migrating_from_vpc_user_to_iam_serviceuser.html.markdown
> +resource "selectel_vpc_user_v2" "service_user" {
Решил остановится на my_service_user :)

2024-03-12 08:49 UTC, saydamir commented on selectel/iam.go
> +func applyServiceUserRoles(ctx context.Context, d *schema.ResourceData, iamClient *iam.Client, rolesToUnassign, rolesToAssign []roles.Role) error {
Эти функции лучше поместить в файлы с ресурсами, т.к. они специфичны для них.

2024-03-12 08:49 UTC, saydamir commented on selectel/iam.go
> +func manageRoles(oldRoles, newRoles []roles.Role) ([]roles.Role, []roles.Role) {
`diffRoles`

2024-03-12 08:49 UTC, saydamir commented on selectel/iam.go
> +	result := make([]interface{}, 0)
nit:
здесь нам известна длина итогового  слайса, так что можно сразу создать с нужным capacity
```suggestion
	result := make([]interface{}, 0, len(roles))
```

2024-03-12 08:49 UTC, saydamir commented on selectel/iam_test.go
> +	type args struct {
Давай табличные тесты приведем к виду описанному в конце [статьи](https://dave.cheney.net/2019/05/07/prefer-table-driven-tests), где имя теста это ключ map, а значение это структура с параметрами для теста.

2024-03-12 08:49 UTC, saydamir commented on selectel/iam_test.go
> +			if !reflect.DeepEqual(actualRolesToUnassign, tt.wantToUnassign) {
У нас же есть в зависимостях testify, давай им тут воспользуемся?

2024-03-12 08:49 UTC, saydamir commented on selectel/resource_selectel_iam_user_v1_test.go
> +	  	role_name = "member"
Может быть в тестах использовать роли, которые доступны до пополнения баланса - reader, billing, iam_admin?

2024-03-12 11:26 UTC, saydamir commented on selectel/resource_selectel_iam_user_v1.go
> +					Type: schema.TypeString,
👍

2024-03-12 13:09 UTC, Icerzack commented on selectel/iam.go
> +func applyServiceUserRoles(ctx context.Context, d *schema.ResourceData, iamClient *iam.Client, rolesToUnassign, rolesToAssign []roles.Role) error {
Да, звучит справедливо, перенес

2024-03-12 13:09 UTC, Icerzack commented on selectel/iam.go
> +func manageRoles(oldRoles, newRoles []roles.Role) ([]roles.Role, []roles.Role) {
Угу, подправил)

2024-03-12 13:10 UTC, Icerzack commented on selectel/iam.go
> +	result := make([]interface{}, 0)
Да кстати, спасибо, исправил!

2024-03-12 13:10 UTC, Icerzack commented on selectel/iam_test.go
> +	type args struct {
Угу, сделано)

2024-03-12 13:10 UTC, icerzack commented on selectel/iam_test.go
> +			if !reflect.DeepEqual(actualRolesToUnassign, tt.wantToUnassign) {
Да, точно)) Переделал на `assert.Equals`

2024-03-12 13:11 UTC, Icerzack commented on selectel/resource_selectel_iam_user_v1_test.go
> +	  	role_name = "member"
В целом, да, будет логичнее, поменял и в `users` и `serviceusers` тестах

2024-03-12 13:17 UTC, saydamir approved these changes

2024-07-05 12:08 UTC, closed without merging